export const WELCOME = 'Welcome'
export const LOGIN_PAGE_GREETING = 'We are glad to see you back with us'
export const USERNAME = 'Username'
export const PASSWORD = 'Password'
export const LOGIN_BUTTON_TEXT = 'Login'
export const PASSWORD_PLACEHOLDER = 'please enter your password'
export const USERNAME_PLACEHOLDER = 'please enter your username'