export const STRINGS_CONSTANT = {
    WELCOME: 'Welcome',
    LOGIN_PAGE_GREETING: 'We are glad to see you back with us',
    USERNAME: 'Username',
    PASSWORD: 'Password',
    LOGIN_BUTTON_TEXT: 'Login',
    PASSWORD_PLACEHOLDER: 'please enter your password',
    USERNAME_PLACEHOLDER: 'please enter your username',
    NIMBLE_LOGDE: 'NimbleLodge',
    GUESTS: 'Guests',
    LISTS: 'Lists',
    ARE: 'are',
    STAYING: 'staying',
    NOW: 'now',
};